name: Test Parachain Progress

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test-parachain-progress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: rustfmt, clippy
        target: wasm32-unknown-unknown
        override: true
        default: true

    - name: Build Code
      run: cargo build --release

    - name: Setup zombienet
      run: source scripts/zombienet_setup.sh

    - name: Update github path
      run: echo "$GITHUB_WORKSPACE/local-network" >> $GITHUB_PATH

    - name: Run parachain progress test
      run: zombienet-linux-x64 test --provider native tests/zombienet/parachain_progress.zndsl

    - name: Prune unused packages from cargo cache
      uses: actions-rs/cargo@v2
      with:
        command: cache
        args: clean-unref

    - name: Prune sources from cargo cache
      uses: actions-rs/cargo@v1
      with:
        command: cache
        args: --autoclean

