name: Test Parachain Progress

on:
  pull_request:
    branches:
    - "main"
    - "bridge-prototype"
  push:
    branches:
    - "main"
    - "bridge-prototype"

jobs:
  test-parachain-progress:
    runs-on: self-hosted
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: rustfmt, clippy
        target: wasm32-unknown-unknown
        override: false
        default: true

    - name: Build Code
      run: cargo build --release

    - name: Setup zombienet
      run: source scripts/zombienet_setup.sh

    - name: Update github path
      run: echo "$GITHUB_WORKSPACE/local-network" >> $GITHUB_PATH

    - name: Run parachain progress test
      run: zombienet-linux-x64 test --provider native tests/zombienet/parachain_progress.zndsl

