name: Test Code

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test-code:
    runs-on: [self-hosted, Linux, X64, large]
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: rustfmt, clippy
        target: wasm32-unknown-unknown
        override: false
        default: true

    - name: Check and Lint Code
      run: cargo clippy -- -D warnings

    - name: Test Code
      run: cargo test

