name: Test Parachain Progress

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test-parachain-progress:
    runs-on: [self-hosted, Linux, X64, large]
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v3

    - name: "Install Rust toolchain"
      uses: Cardinal-Cryptography/aleph-node/.github/actions/install-rust-toolchain@5eda3cd85e7e3aec3f2db7a26631c65d52c4b9ea

    - run: make parachain-progress-test
